# Generated by Django 3.0.6 on 2020-06-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='custom_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='My date'),
        ),
    ]
